services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO
      - --default-time-zone=Asia/Seoul
      - --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/app.cnf:/etc/mysql/conf.d/app.cnf:ro
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: